musicAnalyzer/views/albums.py
from flask import Blueprint, render_template, request
from lyricsgenius import Genius
from musicAnalyzer.models import Album

genius = Genius()

albums = Blueprint("albums", __name__)


@albums.route("/albums", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        return render_template("albums/albums.html")
    else:
        term = request.form["album"]
        return render_template(
            "albums/albums.html",
            results=genius.search_albums(term)["sections"][0]["hits"],
        )


@albums.route("/album")
def album():
    _ = genius.album(int(request.args.get("genius_id")))
    album_ = Album(
        _["album"]["id"],
        _["album"]["name"],
        genius.album_tracks(int(_["album"]["id"]))["tracks"],
    )
    return render_template("albums/album.html", album_=album_)

musicAnalyzer/views/artists.py
from flask import Blueprint, render_template, request
from lyricsgenius import Genius
from musicAnalyzer.models import Artist

artists = Blueprint("artists", __name__)
genius = Genius()


@artists.route("/artists", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        return render_template("artists/artists.html")
    else:
        term = request.form["artist"]
        return render_template(
            "artists/artists.html",
            results=genius.search_artists(term)["sections"][0]["hits"],
        )


@artists.route("/artist")
def artist():
    _ = genius.artist(int(request.args.get("genius_id")))
    artist_ = Artist(
        int(_["artist"]["id"]),
        _["artist"]["name"],
        genius.artist_albums(int(_["artist"]["id"])),
    )
    return render_template("artists/artist.html", artist_=artist_)

musicAnalyzer/templates/artists/artist.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}
{% block body %}
<title>{{ artist_.name }}</title>
<p class="text-center fs-3">{{ artist_.name }}</p>
<div class="row mt-3">
    {% for i in artist_.albums['albums'] %}
    <div class="col-xl-4">
        <div class="p-4 border-bottom text-center">
            <a href="{{ url_for('albums.album', genius_id=i['id']) }}">
                <img class="rounded mb-3" width="200px" height="200px" src="{{ i['cover_art_url'] }}">
                <div>
                    <a class="fs-5 fst-italic" >{{ i['name'] }}</a><br>
                    <span>{{ i['release_date_components']['year'] }}</span>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

musicAnalyzer/templates/artists/artists.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}
{% block body %}
<title>Artists</title>
{{ macros.search_artist_form() }}
<div class="row mt-3">
    {% for i in results %}
    <div class="col-xl-4">
        <div class="mb-3 p-4 text-center border-bottom">
            <a href="{{ url_for('artists.artist', genius_id=i['result']['id']) }}">
                <img class="rounded-circle mb-3" width="100px" height="100px" src="{{ i['result']['image_url'] }}">
                <p class="fs-4">{{ i['result']['name'] }}</p>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}