musicAnalyzer/views/albums.py
from flask import Blueprint, render_template, request
from lyricsgenius import Genius
from musicAnalyzer.models import Album

genius = Genius()

albums = Blueprint("albums", __name__)


@albums.route("/albums", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        return render_template("albums/albums.html")
    else:
        term = request.form["album"]
        return render_template(
            "albums/albums.html",
            results=genius.search_albums(term)["sections"][0]["hits"],
        )


@albums.route("/album")
def album():
    _ = genius.album(int(request.args.get("genius_id")))
    album_ = Album(
        _["album"]["id"],
        _["album"]["name"],
        genius.album_tracks(int(_["album"]["id"]))["tracks"],
    )
    return render_template("albums/album.html", album_=album_)

musicAnalyzer/views/artists.py
from flask import Blueprint, render_template, request
from lyricsgenius import Genius
from musicAnalyzer.models import Artist

artists = Blueprint("artists", __name__)
genius = Genius()


@artists.route("/artists", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        return render_template("artists/artists.html")
    else:
        term = request.form["artist"]
        return render_template(
            "artists/artists.html",
            results=genius.search_artists(term)["sections"][0]["hits"],
        )


@artists.route("/artist")
def artist():
    _ = genius.artist(int(request.args.get("genius_id")))
    artist_ = Artist(
        int(_["artist"]["id"]),
        _["artist"]["name"],
        genius.artist_albums(int(_["artist"]["id"])),
    )
    return render_template("artists/artist.html", artist_=artist_)

musicAnalyzer/views/blogs.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import current_user
from musicAnalyzer.models import Blog
from musicAnalyzer import db
import datetime

blogs = Blueprint("blogs", __name__)


@blogs.route("/blogs")
def index():
    return render_template("blogs/blogs.html", blogs_=Blog.query.all())


@blogs.route("/blog")
def blog():
    blog_ = Blog.query.get(int(request.args.get("id_")))
    return render_template("blogs/blog.html", blog_=blog_)


@blogs.route("/create_blog", methods=["POST"])
def create_blog():
    blog_ = Blog(
        title=request.form["title"],
        date_published=datetime.datetime.now(),
        user_id=current_user.id,
    )
    db.session.add(blog_)
    db.session.commit()
    return redirect(url_for("blogs.editor", id_=blog_.id))


@blogs.route("/editor", methods=["GET", "POST"])
def editor():
    blog_ = Blog.query.get(int(request.args.get("id_")))
    if request.method == "POST":
        blog_.title = request.form["title"]
        blog_.content = request.form["content"]
        db.session.commit()
        return redirect(request.referrer)
    else:
        return render_template("blogs/editor.html", blog_=blog_)


@blogs.route("/delete_blog")
def delete_blog():
    blog_ = Blog.query.get(int(request.args.get("id_")))
    db.session.delete(blog_)
    db.session.commit()
    return redirect(request.referrer)

musicAnalyzer/views/news.py
from flask import Blueprint, render_template, redirect, url_for, request
from musicAnalyzer.models import NewsItem
from musicAnalyzer import db
import datetime
from bs4 import BeautifulSoup
import requests

news = Blueprint("news", __name__)


@news.route("/news")
def index():
    return render_template(
        "news/news.html", news_=NewsItem.query.order_by(db.text("timestamp desc")).all()
    )


@news.route("/suggest_headline", methods=["POST"])
def suggest_headline():
    url = request.form["url"]
    title = BeautifulSoup(requests.get(url).text, "html.parser").find("title")

    return title.get_text()


@news.route("/post_news", methods=["POST"])
def post_news():
    newsitem_ = NewsItem(
        url=request.form["url"],
        headline=request.form["headline"],
        timestamp=datetime.datetime.now(),
    )

    db.session.add(newsitem_)
    db.session.commit()

    return redirect(request.referrer)


@news.route("/edit_news", methods=["POST"])
def edit_news():
    newsitem_ = NewsItem.query.get(int(request.args.get("id_")))
    newsitem_.url = request.form["url"]
    newsitem_.headline = request.form["headline"]
    newsitem_.timestamp = datetime.datetime.now()

    db.session.commit()

    return redirect(request.referrer)


@news.route("/delete_news")
def delete_news():
    newsitem_ = NewsItem.query.get(int(request.args.get("id_")))

    db.session.delete(newsitem_)
    db.session.commit()

    return redirect(request.referrer)

musicAnalyzer/views/songs.py
from flask import Blueprint, render_template, request
from lyricsgenius import Genius

genius = Genius()
songs = Blueprint("songs", __name__)


@songs.route("/songs", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        return render_template("songs/songs.html")
    else:
        term = request.form["song"]
        return render_template(
            "songs/songs.html",
            results=genius.search_songs(term)["hits"],
        )


@songs.route("/song")
def song():
    genius_id = request.args.get("genius_id")
    return render_template(
        "songs/song.html", song_=genius.search_song(song_id=genius_id)
    )

musicAnalyzer/templates/admin.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}
{% block body %}
<title>Admin</title>

{% for i in links_ %}
<div>
    <p>
        <a onclick="$('#submit' + {{ loop.index }}).submit()" class="text-success me-2">+ <i class="bi bi-newspaper"></i></a>
        <span class="badge me-2 {{ i.source_name }}">
            {{ i.source_name }}</span> {{ i.title }}
    </p>
    <form method="POST" action="{{ url_for('news.post_news') }}" id="submit{{ loop.index }}" style="display: none">
        <input autocomplete="off" placeholder="URL" class="form-control w-100 mb-3" name="url" value="{{ i.url }}">
        <input autocomplete="off" placeholder="Headline" class="form-control w-100 mb-3" name="headline" value="{{ i.title }}">
        <button class="btn w-100" type="submit"><i class="bi bi-newspaper"></i> Post News</button>
    </form>
</div>
{% endfor %}
{% endblock %}

musicAnalyzer/templates/album_create.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}

{% block body %}
<title>Albums</title>
<div class="row">
  {{ macros.album_search_results(artist) }}
</div>
{% endblock %}

musicAnalyzer/templates/artist_search.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}

{% block body %}
<title>Artists</title>
<div class="row">
  {{ macros.artist_search_results(results) }}
</div>
{% endblock %}

musicAnalyzer/templates/base.html
<html>
    {% import "macros.html" as macros with context %}
    <head>
        <meta content="width=device-width, initial-scale=1" name="viewport">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.2.0/dist/darkly/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link rel="icon" href="{{ url_for('static', filename='favicon.svg') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    </head>
    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
        <div class="container-fluid">
            <a class="navbar-brand pe-3 border-end" href="{{ url_for('index') }}"><i class="bi bi-soundwave"></i> musicAnalyzer</a>
            <a class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navContent"><i class="bi bi-list"></i></a>
            <div class="collapse navbar-collapse" id="navContent">
                <ul class="navbar-nav me-auto">
                    {% if current_user.role == 'admin' %}
                    <li class="nav-item">
                        <a href="{{ url_for('admin') }}" class="nav-link"><i class="bi bi-key-fill"></i> Admin</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{{ url_for('news.index') }}" class="nav-link">News</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('blogs.index') }}" class="nav-link">Blogs</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a data-bs-toggle="dropdown" data-bs-target="#music" class="nav-link dropdown-toggle">Music</a>
                        <div id="music" class="dropdown-menu text-center">
                            <a class="dropdown-item" href="{{ url_for('artists.index') }}">Artists</a>
                            <a class="dropdown-item" href="{{ url_for('albums.index') }}">Albums</a>
                            <a class="dropdown-item" href="{{ url_for('songs.index') }}">Songs</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" data-bs-target="#user"><i class="bi bi-person-fill"></i></a>
                        <div id="user" class="dropdown-menu dropdown-menu-end text-center">
                            {% if current_user.is_anonymous %}
                            <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#login">Log In</a>
                            <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#signup">Sign Up</a>
                            {% else %}
                            <a class="dropdown-item" href="{{ url_for('logout') }}">Log Out</a>
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="modal" id="login">
        <div class="modal-dialog">
            <div class="modal-content p-4">
                {{ macros.login_form() }}
            </div>
        </div>
    </div>
    
    <div class="modal" id="signup">
        <div class="modal-dialog">
            <div class="modal-content p-4">
                {{ macros.signup_form() }}
            </div>
        </div>
    </div>
    
    <div class="container py-5" id="pageContent">
        {% block body %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='main.js') }}"></script>
    </div>
</html>

musicAnalyzer/templates/blogs.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}
{% block body %}
<title>Blogs</title>
{% if not current_user.is_anonymous %}{{ macros.add_blog_form() }}{% endif %}
<div class="row mt-3">
    {% for i in blogs_ %}
    {{ macros.blog_card(i) }}
    {% endfor %}
</div>
{% endblock %}

musicAnalyzer/templates/index.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}
{% block body %}
<title>musicAnalyzer</title>
{% if news_ | length >= 5 %}
<div>
    <div class="col-xl-12">
        <div class="h-50 border-bottom m-3 p-3">
            <a target="blank_" href="{{ news_[0].url }}" class="fs-3">{{ news_[0].headline }}</a>
        </div>
    </div>
    <div class="row">
        {% for i in news_[1:5] %}
        <div class="col-xl-3">
            <div class="border-bottom m-3 p-3" style="height: 150px">
                <a target="blank_" href="{{ i.url }}" class="fs-5">{{ i.headline }}</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-xl-6">
        <p class="text-center fs-5 m-0 fst-italic text-danger mt-5">TOP 10</p>
        {% for i in charts[:10] %}
        <div class="col-12">
            <div class="p-4 border-bottom">
                <p class="fst-italic fs-5 m-0">{{ i.title }}</p>
                <span class="fw-light text-muted">{{ i.artist }}</span>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-xl-6">
        <p class="text-center fs-5 m-0 fst-italic text-danger mt-5">HOT & FRESH</p>
        {% for i in hot[:10] %}
        <div class="col-12">
            <div class="p-4 border-bottom">
                <p class="fst-italic fs-5 m-0">{{ i.title }}</p>
                <span class="fw-light text-muted">{{ utc_to_time(i.created_utc).strftime('%-m/%-d/%y %-I:%M %p') }}</span>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

musicAnalyzer/templates/macros.html
{% macro blog_card(blog_) %}
<div class="col-xl-4">
    <div class="p-4 border-bottom">
        <a class="fs-5" href="{{ url_for('blogs.blog', id_=blog_.id) }}">{{ blog_.title }}</a><br>
        <a>{{ blog_.users.username }}</a><br>
        <span class="text-muted">{{ blog_.date_published.strftime('%-m/%-d/%y %-I:%M %p') }}</span>
        {% if current_user.id == blog_.user_id %}
        <div class="mt-3">
            <a class="me-2" href="{{ url_for('blogs.editor', id_=blog_.id) }}"><i class="bi bi-pen"></i></a>
            <a class="text-danger" onclick="toggleDiv('deleteBlog' + {{ blog_.id }})"><i class="bi bi-trash3"></i></a>
            <a style="display: none" id="deleteBlog{{ blog_.id }}" class="text-danger" href="{{ url_for('blogs.delete_blog', id_=blog_.id) }}">Delete?</a>
        </div>
        {% endif %}
    </div>
</div>
{% endmacro %}

{% macro login_form() %}
<form method="POST" action="{{ url_for('login') }}">
    <input class="form-control w-100 mb-3" placeholder="Username" name="username" autocomplete="off">
    <input class="form-control w-100 mb-3" placeholder="Password" name="password" autocomplete="off" type="password">
    <button class="btn w-100" type="submit">Log In</button>
</form>
{% endmacro %}

{% macro signup_form() %}
<form method="POST" action="{{ url_for('signup') }}">
    <input class="form-control w-100 mb-3" placeholder="Username" name="username" autocomplete="off">
    <input class="form-control w-100 mb-3" placeholder="Password" name="password" autocomplete="off" type="password">
    <button class="btn w-100" type="submit">Sign Up</button>
</form>
{% endmacro %}

{% macro search_artist_form() %}
<form class="input-group" method="POST" action="{{ url_for('artists.index') }}">
    <input autocomplete="off" placeholder="Search Artists" class="form-control" name="artist">
    <button class="btn" type="submit"><i class="bi bi-search"></i></button>
</form>
{% endmacro %}

{% macro search_album_form() %}
<form class="input-group" method="POST" action="{{ url_for('albums.index') }}">
    <input autocomplete="off" placeholder="Search Albums" class="form-control" name="album">
    <button class="btn" type="submit"><i class="bi bi-search"></i></button>
</form>
{% endmacro %}

{% macro search_song_form() %}
<form class="input-group" method="POST" action="{{ url_for('songs.index') }}">
    <input autocomplete="off" placeholder="Search Songs" class="form-control" name="song">
    <button class="btn" type="submit"><i class="bi bi-search"></i></button>
</form>
{% endmacro %}

{% macro post_news_form() %}
<form method="POST" action="{{ url_for('news.post_news') }}">
    <input onchange="suggestHeadline()" autocomplete="off" placeholder="URL" class="form-control w-100 mb-3" name="url" id="url">
    <input autocomplete="off" placeholder="Headline" class="form-control w-100 mb-3" name="headline" id="headline">
    <button class="btn w-100" type="submit"><i class="bi bi-newspaper"></i> Post News</button>
</form>
{% endmacro %}

{% macro edit_news_form(newsitem_) %}
<form method="POST" action="{{ url_for('news.edit_news', id_=newsitem_.id) }}">
    <input autocomplete="off" placeholder="URL" class="form-control w-100 mb-3" name="url" value="{{ newsitem_.url }}">
    <input autocomplete="off" placeholder="Headline" class="form-control w-100 mb-3" name="headline" value="{{ newsitem_.headline }}">
    <button class="btn w-100" type="submit"><i class="bi bi-newspaper"></i> Edit News</button>
</form>
{% endmacro %}

{% macro create_blog_form() %}
<form method="POST" action="{{ url_for('blogs.create_blog') }}" class="input-group">
    <input autocomplete="off" placeholder="Title" class="form-control" name="title">
    <button class="btn" type="submit">Create Blog</button>
</form>
{% endmacro %}

{% macro blog_editor(blog_) %}
<form method="POST" action="{{ url_for('blogs.editor', id_=blog_.id) }}">
    <input autocomplete="off" placeholder="Title" class="form-control mb-3" name="title" value="{{ blog_.title }}">
    <textarea rows="25" autocomplete="off" placeholder="Content" class="form-control mb-3" name="content">{{ blog_.content }}</textarea>
    <button class="btn w-100" type="submit">Save</button>
</form>
{% endmacro %}