musicAnalyzer/views/news.py
from flask import Blueprint, render_template, redirect, url_for, request
from musicAnalyzer.models import NewsItem
from musicAnalyzer import db
import datetime
from bs4 import BeautifulSoup
import requests

news = Blueprint("news", __name__)


@news.route("/news")
def index():
    return render_template(
        "news/news.html", news_=NewsItem.query.order_by(db.text("timestamp desc")).all()
    )


@news.route("/suggest_headline", methods=["POST"])
def suggest_headline():
    url = request.form["url"]
    title = BeautifulSoup(requests.get(url).text, "html.parser").find("title")

    return title.get_text()


@news.route("/post_news", methods=["POST"])
def post_news():
    newsitem_ = NewsItem(
        url=request.form["url"],
        headline=request.form["headline"],
        timestamp=datetime.datetime.now(),
    )

    db.session.add(newsitem_)
    db.session.commit()

    return redirect(request.referrer)


@news.route("/edit_news", methods=["POST"])
def edit_news():
    newsitem_ = NewsItem.query.get(int(request.args.get("id_")))
    newsitem_.url = request.form["url"]
    newsitem_.headline = request.form["headline"]
    newsitem_.timestamp = datetime.datetime.now()

    db.session.commit()

    return redirect(request.referrer)


@news.route("/delete_news")
def delete_news():
    newsitem_ = NewsItem.query.get(int(request.args.get("id_")))

    db.session.delete(newsitem_)
    db.session.commit()

    return redirect(request.referrer)

musicAnalyzer/templates/news/news.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}
{% block body %}
<title>News</title>
{% if current_user.role == 'admin' %}{{ macros.post_news_form() }}{% endif %}
<div class="row mt-3">
    {% for i in news_ %}
    <div class="col-xl-4">
        <div class="p-4 border-bottom">
            <a class="fs-5" target="_blank" href="{{ i.url }}">{{ i.headline }}</a><br>
            <span class="fst-italic text-muted">{{ i.timestamp.strftime('%-m-%-d-%y %-I:%M %p') }}</span>
            {% if current_user.role == 'admin' %}
            <div class="mt-3">
                <a class="mx-1" onclick="toggleDiv('editNews' + {{ i.id }})"><i class="bi bi-pen"></i></a>
                <a class="text-danger" onclick="toggleDiv('deleteNews' + {{ i.id }})"><i class="bi bi-trash3"></i></a>
                <a style="display: none" id="deleteNews{{ i.id }}" class="text-danger" href="{{ url_for('news.delete_news', id_=i.id) }}">Delete?</a>
                <div class="mt-3" id="editNews{{ i.id }}" style="display: none">{{ macros.edit_news_form(i) }}</div>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}