musicAnalyzer/views/albums.py
from flask import Blueprint, render_template, request
from lyricsgenius import Genius
from musicAnalyzer.models import Album

genius = Genius()

albums = Blueprint("albums", __name__)


@albums.route("/albums", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        return render_template("albums/albums.html")
    else:
        term = request.form["album"]
        return render_template(
            "albums/albums.html",
            results=genius.search_albums(term)["sections"][0]["hits"],
        )


@albums.route("/album")
def album():
    _ = genius.album(int(request.args.get("genius_id")))
    album_ = Album(
        _["album"]["id"],
        _["album"]["name"],
        genius.album_tracks(int(_["album"]["id"]))["tracks"],
    )
    return render_template("albums/album.html", album_=album_)

musicAnalyzer/views/songs.py
from flask import Blueprint, render_template, request
from lyricsgenius import Genius

genius = Genius()
songs = Blueprint("songs", __name__)


@songs.route("/songs", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        return render_template("songs/songs.html")
    else:
        term = request.form["song"]
        return render_template(
            "songs/songs.html",
            results=genius.search_songs(term)["hits"],
        )


@songs.route("/song")
def song():
    genius_id = request.args.get("genius_id")
    return render_template(
        "songs/song.html", song_=genius.search_song(song_id=genius_id)
    )

musicAnalyzer/templates/albums/album.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}
{% block body %}
<title>{{ album_.title }}</title>
<p class="text-center fs-3">{{ album_.title }}</p>
<div class="row mt-3">
    {% for i in album_.songs %}
    <div class="col-xl-12">
        <div class="p-4 border-bottom">
            <a href="{{ url_for('songs.song', genius_id=i['song']['id']) }}"><span class="me-3 text-danger">{{ loop.index }}</span> {{ i['song']['title_with_featured'] }}</a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

musicAnalyzer/templates/albums/albums.html
{% extends "base.html" %}
{% import "macros.html" as macros with context %}
{% block body %}
<title>Albums</title>
{{ macros.search_album_form() }}
<div class="row mt-3">
    {% for i in results %}
    <div class="col-xl-4">
        <div class="p-4 border-bottom text-center">
            <a href="{{ url_for('albums.album', genius_id=i['result']['id']) }}">
                <img class="rounded mb-3" width="200px" height="200px" src="{{ i['result']['cover_art_url'] }}">
                <div>
                    <a class="fs-5 fst-italic" >{{ i['result']['name'] }}</a><br>
                    <span>{{ i['result']['release_date_components']['year'] }}</span>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}